# Generated by Django 2.1 on 2019-04-30 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='College Name', max_length=50)),
                ('Location', models.CharField(default='Example, IA', max_length=50)),
                ('Student_Slots', models.IntegerField(null=True)),
                ('Domain', models.CharField(default='@example.edu', max_length=50)),
                ('ISD_Name', models.CharField(default='Kevin', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ISD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISD_Email', models.EmailField(default='', max_length=100)),
                ('college', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='colleges.College')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.EmailField(default='UserName', max_length=100)),
                ('Nationality', models.CharField(default='Country', max_length=50)),
                ('Major', models.CharField(default='Major', max_length=50)),
                ('Language', models.CharField(default='English', max_length=50)),
                ('Age', models.PositiveIntegerField(null=True)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='colleges.College')),
            ],
        ),
    ]
