# Generated by Django 2.1 on 2019-04-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='ISD_Name',
        ),
        migrations.RemoveField(
            model_name='isd',
            name='ISD_Email',
        ),
        migrations.AddField(
            model_name='college',
            name='ISD_Email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
