# Generated by Django 2.1 on 2019-04-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_auto_20190429_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='isd',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
