# Generated by Django 2.1 on 2019-04-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_auto_20190429_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='User_Name',
        ),
        migrations.AddField(
            model_name='student',
            name='User_Email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='ISD_Email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='Location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Nationality',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
