# Generated by Django 2.1 on 2019-04-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_auto_20190429_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='Student_Slots',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
